name: ci

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - 'release/**'

jobs:  
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.4'
      
      - name: Install dependencies
        run: go mod download
        working-directory: uv-server

      - name: Build build_packet utility
        run: go build -v ./cmd/build_packet

      - name: Generate protocol/types.js file
        run: ./uv-server/build_packet.exe export-type ./src/protocol

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run package

